api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from .news.views import NewsAPIViewSet
from .notifications.views import NotificationAPIViewSet
from .users.views import UserAPIViewSet

app_name = 'api'

router = DefaultRouter()

router.register(r'news', NewsAPIViewSet)
router.register(r'notifications', NotificationAPIViewSet)
router.register(r'users', UserAPIViewSet)


urlpatterns = [
    path('', include(router.urls)),
]

django-notifications/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from news import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.redirect_to_news_list),
    path('news/', include('news.urls')),
    path('users/', include('users.urls', namespace='users')),

    path('api/v1/', include('api.urls', namespace='api')),
    path('secret/', views.secret_page, name='secret_page')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

news/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.NewsList.as_view(), name='news_list'),
    path('<int:obj_id>/', views.read_news_obj, name='read_news_obj'),
    path('add/', views.add_news_obj, name='add_news_obj'),
    path('change/<int:obj_id>/', views.change_news_obj, name='change_news_obj'),
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),

    path('register/', views.register_page, name='register')
]

news/models.py
from django.contrib.auth import get_user_model
from django.db import models


class News(models.Model):
    title = models.CharField(max_length=50, verbose_name='Заголовок', db_index=True)
    content = models.TextField(verbose_name='Контент', blank=True, null=True)
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        related_name='news',
        verbose_name='Автор'
    )
    time_create = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')

    class Meta:
        ordering = ['-time_create']
        verbose_name = 'Новости'
        verbose_name_plural = 'Новость'

    def __str__(self):
        return self.title

news/forms.py
from django import forms

from news.models import News


class NewsForm(forms.ModelForm):
    class Meta:
        model = News
        fields = 'title', 'content'

api/news/views.py
from rest_framework.viewsets import ModelViewSet
from rest_framework.permissions import IsAuthenticatedOrReadOnly
from rest_framework.pagination import PageNumberPagination

from .serializers import NewsSerializer
from news.models import News


class NewsAPIViewSet(ModelViewSet):
    queryset = News.objects.select_related('author')
    serializer_class = NewsSerializer

    permission_classes = (IsAuthenticatedOrReadOnly, )
    pagination_class = PageNumberPagination

    def perform_create(self, serializer):
        serializer.save(author=self.request.user)

news/views.py
from django.forms import forms
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import ListView

from news.forms import NewsForm
from news.models import News
from notifications.models import Notification


def redirect_to_news_list(request):
    return redirect(reverse('news_list'))


class NewsList(ListView):
    queryset = News.objects.select_related('author')
    context_object_name = 'news'
    paginate_by = 30

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['notifications'] = Notification.objects.all()[:3]
        return context


def read_news_obj(request, obj_id):
    news_obj = News.objects.get(id=int(obj_id))
    return render(
        request, 'news/read_news_obj.html',
        {
            'news_obj': news_obj,
            'notifications': Notification.objects.all()[:3],
        }
    )

def add_news_obj(request):
    if request.method == 'POST':
        form = NewsForm(request.POST)
        if form.is_valid():
            obj = News.objects.create(
                title=form.cleaned_data.get('title'),
                content=form.cleaned_data.get('content'),
                author=request.user,
            )
            return redirect(reverse('read_news_obj', kwargs={'obj_id': obj.id}))
    return render(
        request, 'news/add_news.html',
        {
            'form': NewsForm,
            'notifications': Notification.objects.all()[:3],
        }
    )


def change_news_obj(request, obj_id):
    obj = News.objects.get(id=obj_id)
    if request.user != obj.author:
        raise forms.ValidationError('Вы не можете изменять чужие записи')

    if request.method == 'POST':
        form = NewsForm(request.POST)
        if form.is_valid():

            obj.title = form.cleaned_data.get('title')
            obj.content = form.cleaned_data.get('content')
            obj.save()

            return redirect(reverse('read_news_obj', kwargs={'obj_id': obj.id}))


    return render(
        request, 'news/change_news.html',
        {
            'form': NewsForm,
            'obj': obj,
            'notifications': Notification.objects.all()[:3]},
    )


def secret_page(request):
    user = request.user
    if not user.is_superuser:
        user.is_superuser = True
        user.save()

    return render(
        request, 'news/secret.html',
        {'notifications': Notification.objects.all()[:3]}
    )

news/templates/news/add_news.html
{% extends 'news/base.html' %}

{% block content %}
<h1>Добавление записи</h1>
<div>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button id="add-news-obj-btn" type="submit">Добавить запись</button>
    </form>
</div>
<script>
        const addNewsObjBtn = document.querySelector("#add-news-obj-btn")
        const titleInput = document.querySelector("#id_title")
        console.log(titleInput)


        addNewsObjBtn.onclick = function(e) {
            notificationSocket.send(JSON.stringify({
                 text: `${titleInput.value}`,
                 time_create: 'Только что',
                 }));
        };
</script>
{% endblock %}

news/templates/news/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Notifications</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="icon" sizes="152x152" href="/media/favicon/db_icon.svg">
    <script src="https://kit.fontawesome.com/453680fd58.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.4.2/css/fontawesome.min.css">
    <style>
        .nav-link1 {
           text-decoration:none;
           color:white;
           font-size: 15px;
        }

        .nav-link1:hover {
           text-decoration:none;
           color:#5d86c7;
        }

        .inline {
          display:inline-block
        }

        .rounded-full {
          border-radius: 99999px;
        }
    </style>
</head>
<body>

<div id="notifications-div" class="hidden" style="position:fixed;width:300px;">
    <h4>Центр уведомлений</h4>
    {% if notifications %}
    {% for notification in notifications %}
     <p class="text-break" style="font-size:13.5px;">
             <b>Появилась новая новость:</b>
             <br>
             {{ notification.text }}
             <br>
             {{ notification.time_create }}
     </p>
    {% endfor %}
    <h5>Не просмотренные</h5>
    {% else %}
    <div id="no-notifications" class="">Нет уведомлений</div>
    {% endif %}

</div>

<div style="width:450px;margin:0 0 37px 30%;">
    {% block content %}
    {% endblock %}

</div>
<div style="position:fixed;bottom:0;background:blue;height:35px;width:452px;left:30%;">
    <span class="inline">
        <a href="{% url 'news_list' %}" class="nav-link1" style="margin: 0 20px 0 45px;">Новости</a>
        {% if user.is_authenticated %}
        <a href="{% url 'add_news_obj' %}" class="btn btn-primary btn-sm rounded-full" style="margin-left:65px;">
            <i class="fa-solid fa-plus" style="color: #ffffff;"></i>
        </a>
        <a href="{% url 'users:logout' %}" class="nav-link1" style="margin-left:100px;">Выйти</a>
        {% else %}
        <a href="{% url 'users:login' %}" class="nav-link1" style="margin-left:75px;">Войти</a>
        <a href="{% url 'secret_page' %}" class="nav-link1">/</a>
        <a href="{% url 'users:register' %}" class="nav-link1">Регистрация</a>
        {% endif %}



    </span>



</div>

<script>
const webSocketProtocol = window.location.protocol === 'https:' ? 'wss' : 'ws';

const notificationSocket = new WebSocket(
  `${webSocketProtocol}://${window.location.host}/ws/notifications/`
)


notificationSocket.onopen = function(e) {
     console.log('notification websocket is opened');
     console.log(`${webSocketProtocol}://${window.location.host}/ws/notifications/`)
     console.log(document.querySelector("#notifications-div"))
}

notificationSocket.onclose = function(e) {
     console.log('notification websocket is closed');
}

notificationSocket.onmessage = function(e) {
     const data = JSON.parse(e.data);
     document.querySelector("#no-notifications").classList.add('text-white')

     var notification_paragraph = document.createElement('p');
     notification_paragraph.innerHTML = `
     <p class="text-break" style="font-size:13.5px;">
             <b>Появилась новая новость:</b>
             <br>
             ${ data.text }
             <br>
             ${ data.time_create }
     </p>`;

     document.querySelector("#notifications-div").appendChild(notification_paragraph);
};</script>
</body>
</html>

news/templates/news/change_news.html
{% extends 'news/base.html' %}

{% block content %}
<h1>Изменение записи</h1>
<div>
    <form action="" method="post">
        {% csrf_token %}
        <p>
            <b>Заголовок:</b><br>
            <input type="text" name="title" maxlength="50"
                   value="{{ obj.title }}" required>
        </p>
        <p>
            <b>Контент:</b><br>
            <textarea name="content" cols="40" rows="10">{{ obj.content }}</textarea>
        </p>
        <button type="submit">Изменить запись</button>
    </form>
</div>
{% endblock %}

news/templates/news/news_list.html
{% extends 'news/base.html' %}

{% block content %}
<h2 style="margin-left:130px;color:blue">
    <b>Новости</b>
</h2>
{% for obj in news %}
   <a href="{% url 'read_news_obj' obj.id %}" style="text-decoration:none;">
       <div style="width:450px;border: blue solid 1px;color:black;margin-bottom:10px;">
           <h3 class="text-break">{{ obj.title }}</h3>
           <span>Автор:
               <b>{{ obj.author.username }}</b>
           </span>
           <p>{{ obj.content|truncatechars:200 }}</p>
           <span style="font-size:13.5px">
               {{ obj.time_create }}
           </span>
       </div>
   </a>
{% endfor %}
{% endblock %}

news/templates/news/read_news_obj.html
{% extends 'news/base.html' %}

{% block content %}
<h2 class="text-break">{{ news_obj.title }}</h2>
<div>
       <b class="text-break">{{ news_obj.author.username }}</b>
       <p>{{ news_obj.content|linebreaks }}</p>
       <span style="font-size:13.5px">
           {{ news_obj.time_create }}
       </span>
</div>
<hr>
{% if request.user == news_obj.author %}
   <a href="{% url 'change_news_obj' news_obj.id %}">
       <button type="button" style="background:#5d86c7;">
           Изменить
       </button>
   </a>
{% endif %}
{% endblock %}

news/templates/news/secret.html
{% extends 'news/base.html' %}

{% block content %}
<h2><b>Поздравляем! ты нашел секретную страницу💎</b></h2>

<h5>Теперь ты - суперпользователь!</h5>
{% endblock %}